# Generated by Django 5.0.6 on 2026-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addattedence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addattedance",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
