# Generated by Django 5.0.6 on 2026-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Takeattedence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("status", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
