# Generated by Django 5.0.6 on 2026-03-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takeattedence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takeattedence",
            name="status",
            field=models.CharField(max_length=100),
        ),
    ]
